### ISSUE TITLE
Add configurable user-service address

### ISSUE THREAD

**Issue by omrishtam** [meateam/authentication-service#16]
There's an hard coded address, with a port that we didn't agree on, in client connection in [`user.rpc.ts`](https://github.com/meateam/authenticator/blob/f111ff641809795b5376599ea2df03c3921c8a0d/src/user/user.rpc.ts#L17).

There should be a configurable address for it, and the [user-service default port](https://github.com/meateam/user-service/blob/ec68a07c4fabeeed58d27b042bdb851236e8da3a/src/index.ts#L22) should be changed to the agreed port as well.

**Comment by AllKinds** [comment]
We don't call the user-service from the authentication-service any more.
